sudo: required

language: python

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

python:
  - "3.5"
  
cache: pip
  
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py develop
  
# command to run tests
script:
  - python Pyfhel/test.py
